on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: esalab
      uses: SamKirkland/FTP-Deploy-Action@master
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }} 
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /ftp_data/www/esalab/
        protocol: ftps
